# SPDX-License-Identifier: Apache-2.0
"""Write a local practice profile with an active skill selection."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from skills.loader import DEFAULT_SKILL, list_available_skills, load_skill  # noqa: E402


PROFILE_FIELDS: dict[str, Any] = {
    "active_skill": DEFAULT_SKILL,
    "role": None,
    "deal_size_range": None,
    "crm": None,
    "call_platform": None,
    "avg_cycle_days": None,
    "aq_ratio_baseline": None,
    "aq_thresholds": None,
    "board_metric": None,
    "competitor_categories": [],
}


def _yaml_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return json.dumps(value)
    return json.dumps(str(value))


def render_profile(fields: dict[str, Any]) -> str:
    rows = [
        "# Local Revenue Intelligence Practice Profile",
        "",
        "<!-- SPDX-License-Identifier: Apache-2.0 -->",
        "",
        "This file is generated by `tools/cold_start.py` and is ignored by git.",
        "It contains local operator configuration only; do not commit it.",
        "",
        "```yaml",
    ]
    for key in PROFILE_FIELDS:
        rows.append(f"{key}: {_yaml_value(fields.get(key))}")
    rows.extend(
        [
            "```",
            "",
            "Drafts, not decisions. Verify agent and cookbook outputs before acting.",
        ]
    )
    return "\n".join(rows) + "\n"


def _coerce_number(raw: str) -> int | float | None:
    raw = raw.strip()
    if not raw:
        return None
    try:
        value = float(raw)
    except ValueError:
        return None
    if value.is_integer():
        return int(value)
    return value


def _prompt(label: str, default: Any = None) -> Any:
    suffix = "" if default is None else f" [{default}]"
    raw = input(f"{label}{suffix}: ").strip()
    return default if not raw else raw


def collect_interactive_fields(root: Path, selected_skill: str | None = None) -> dict[str, Any]:
    skills = list_available_skills(root)
    if not skills:
        raise SystemExit("No installed motion skills found.")
    print("Available skills:")
    for skill in skills:
        print(f"- {skill.name}: {skill.description}")

    fields = dict(PROFILE_FIELDS)
    fields["active_skill"] = selected_skill or _prompt("active_skill", DEFAULT_SKILL)
    load_skill(str(fields["active_skill"]), root)

    fields["role"] = _prompt("role", None)
    fields["deal_size_range"] = _prompt("deal_size_range", None)
    fields["crm"] = _prompt("crm", None)
    fields["call_platform"] = _prompt("call_platform", None)
    fields["avg_cycle_days"] = _coerce_number(str(_prompt("avg_cycle_days", "")))
    fields["aq_ratio_baseline"] = _coerce_number(str(_prompt("aq_ratio_baseline", "")))
    fields["board_metric"] = _prompt("board_metric", None)
    categories = _prompt("competitor_categories comma-separated", "")
    if categories:
        fields["competitor_categories"] = [
            item.strip() for item in str(categories).split(",") if item.strip()
        ]
    return fields


def write_profile(profile_path: Path, fields: dict[str, Any], *, force: bool = False) -> Path:
    if profile_path.exists() and not force:
        raise FileExistsError(f"{profile_path} already exists; pass --force to overwrite")
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    profile_path.write_text(render_profile(fields), encoding="utf-8")
    return profile_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skill", default=None, help="Installed skill id to select.")
    parser.add_argument("--profile-path", type=Path, default=ROOT / "CLAUDE.local.md")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing profile.")
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Write defaults plus --skill without prompting.",
    )
    args = parser.parse_args(argv)

    root = ROOT
    if args.non_interactive:
        fields = dict(PROFILE_FIELDS)
        fields["active_skill"] = args.skill or DEFAULT_SKILL
        load_skill(str(fields["active_skill"]), root)
    else:
        fields = collect_interactive_fields(root, args.skill)

    path = write_profile(args.profile_path, fields, force=args.force)
    print(f"wrote {path}")
    print(f"active_skill: {fields['active_skill']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
